---
title: "Projet INLO"
author: "DIENY, CRISTIANINI, GIRAUD"
date: "11 octobre 2018"
output: html_document
---
[comment]: # It could be intersting to have a couple of lines at first talking about what's your main objectif, and try to make complete comrehensible and clear phrases rather than enumarating vague terms without a definite context. 

#Description du sujet:

 La partie statistiques consiste à établir le type de test statistique qu'il faut appliqué en fonction des données que l'on utilise (apparié / non-apparié). De plus il faudra déterminer l'algorythme à appliquer pour les relations de phylogénies. De plus il faudra faire attention à la faisabilité des analyses statistiques, tristan le trou d'cul on ne peux pas faire des tests statistiques sur des données qui ne sont pas similaires ou si une partie des données n'est pas présente dans le cluster.



# Obtention des informations:

## Choix des critères génétique

C'est à nous de faire la matrice de transition ? (à priori non)
Combien de donnée avec les critères choisies?
 * sequence UTR
 * liste des isoformes par gêne
 * régulation
 * contenue nucléotidique (en lettre)
 * matrice des transitions
 * matrice des transitions (ex: proba quand on a un A d’avoir ensuite un T)
 * richesse en GC
 * structure 3D 
 * liste des isoformes
 * Conservations
 * Elements et régions régulatrices
 * Séquences codantes
 * Longueur en exon
 * Distance entre deux gènes

--> Il faudrait faire une "réunion" avec les génomisciens pour la pertinence des critères et leur priorités
--> Etudier les conservations des gènes à travers les espèces (organismes eucaryotes en général)
--> Notion d'orthologie

## Donnée clinique

 * Séquençage génome humain (mutation/variant) et maladies associés (Dossier médical)
 * Variant : polimorphisme/mutation somatique


## Méthode d'obtention

single cell?
suffisament de données?
à priori oui et non, il va falloir faire un choix, car :
 - si optention avec singlecell: moins de données (focéments car récent) mais très bon pour du deep learning
 - Si optention sans single cell: beaucoup plus dee données mais moins précise: il serais préférable de faire un modele linéiaire généralisé. Au quel cas, pour construire le modèle:
 - Quel sensibilité/spécificité ?

--> Lidéal est de prendre toute les données (single cell ou non) et de faire un modele, on oublie le deep learning, sauf si beaucoup de donnée en singlecell (au moins 10 000 vu tout les critres)


# Phylogénie

Choisir l'algorythme pour calculer la distance entre 2 gênes


# Tests statistiques

## Test de corélation/Student:

Effectuer un test de corrélation entre les critères choisies. Ont peut aussi effectuer un test de student 
Test de Ficher

#Pipeline d'analyses statistiques ?

Graphiques pertinent -> Lesquels ?

###### Questions cahier des charges_stats

1: Série de questions sur les données / entrée avec paramètres réglables et modifiable au loisir de l'utilisateurs ? Au choix
2: Les graphiques, dans quel mesure, leur pertinence, sont ils indispensables, lesquels sont obligatoires, lesquels faut-il absolument garder ? 
3: Une p-value de base à 0.05 ou bien faut-il etre en mesure de la modifier (ATTENTION A LA PERTINENCE) 
4: Séquences protéiques?
5: Doit on dresser un arbre?

(Blast à la volée ou a l’insertion ?)

####Conseils :

Caractériser les differents tests, dans quesl circonstances (para/non paramétrique)
Scatter plot avant corrélation (anscombe quartet)
Après test anova (ou kruskal wallis) il faut faire un test (post-hoc ?)
Il faut voir avec les génomiciens les critères ils sont capables de récupérer pour etre capable de faire des stats sur les même choses.

Quel algo pour la phylogénie ? 
